# Information about where the book exists on the web
repository:
  url: https://github.com/KTFish/DCGAN.git # Online location of your book
  path_to_book: dcgan.ipynb # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)
